[package]
name = "tuGit"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "tuGit"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.10.1"
git2 = "0.18.2"

[dev-dependencies]
marine-rs-sdk-test = "0.12.0"
