[package]
name = "tu_volumes"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "tu_volumes"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.10.3"
serde_json = "*"
tu_types = { path = "../../tuTypes" }


[dev-dependencies]
marine-rs-sdk-test = "0.16.0"
